import { router, json, error, secrets } from '@appdeploy/sdk';

const SUPABASE_URL = 'https://mthoghfbhehwiwuxpikq.supabase.co';
async function key(){ return await secrets.readSecret('SUPABASE_SERVICE_ROLE_KEY'); }
async function sb(path:string, init:RequestInit={}){ const k=await key(); const headers=new Headers(init.headers); headers.set('apikey',k); if(!headers.has('Content-Type') && init.body) headers.set('Content-Type','application/json'); const r=await fetch(`${SUPABASE_URL}${path}`,{...init,headers}); const text=await r.text(); let data:any=null; try{data=text?JSON.parse(text):null}catch{data=text} return {r,data}; }
async function userFrom(ctx:any){ const token=String(ctx.event?.headers?.authorization||ctx.event?.headers?.Authorization||'').replace(/^Bearer\s+/i,''); if(!token) return null; const {r,data}=await sb('/auth/v1/user',{headers:{Authorization:`Bearer ${token}`}}); return r.ok?data:null; }
async function adminFrom(ctx:any){ const u=await userFrom(ctx); if(!u?.id)return null; const {r,data}=await sb(`/rest/v1/profiles?id=eq.${encodeURIComponent(u.id)}&select=id,role&limit=1`); return r.ok&&data?.[0]?.role==='admin'?u:null; }
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const handler=router({
 'GET /api/health':[async()=>json({ok:true,service:'crave-house-appdeploy-api'})],
 'POST /api/auth/signup':[async({body})=>{const b=body as any;if(!b?.email||!b?.password||!b?.full_name)return error('Name, email and password are required',400);if(String(b.password).length<8)return error('Password must be at least 8 characters',400);const k=await key();const r=await fetch(`${SUPABASE_URL}/auth/v1/otp`,{method:'POST',headers:{apikey:k,'Content-Type':'application/json'},body:JSON.stringify({email:String(b.email).trim().toLowerCase(),create_user:true,data:{full_name:String(b.full_name).trim()}})});const d=await r.json();return r.ok?json({ok:true,verification_required:true,message:'Verification code sent'}):error(d.msg||d.error_description||'Could not send verification code',400)}],
 'POST /api/auth/verify-signup':[async({body})=>{const b=body as any;if(!b?.email||!b?.token||!b?.password)return error('Email, verification code and password are required',400);const k=await key();const vr=await fetch(`${SUPABASE_URL}/auth/v1/verify`,{method:'POST',headers:{apikey:k,'Content-Type':'application/json'},body:JSON.stringify({email:String(b.email).trim().toLowerCase(),token:String(b.token).trim(),type:'email'})});const vd=await vr.json();if(!vr.ok)return error(vd.msg||vd.error_description||'Invalid verification code',400);if(vd.access_token){const ur=await fetch(`${SUPABASE_URL}/auth/v1/user`,{method:'PUT',headers:{apikey:k,Authorization:`Bearer ${vd.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({password:b.password,data:{full_name:b.full_name||''}})});if(!ur.ok)return error('Email verified, but account setup could not be completed. Please sign in.',500)}return json({access_token:vd.access_token,refresh_token:vd.refresh_token,user:vd.user})}],
 'POST /api/auth/resend':[async({body})=>{const b=body as any;if(!b?.email)return error('Email is required',400);const k=await key();const r=await fetch(`${SUPABASE_URL}/auth/v1/otp`,{method:'POST',headers:{apikey:k,'Content-Type':'application/json'},body:JSON.stringify({email:String(b.email).trim().toLowerCase(),create_user:false})});const d=await r.json();return r.ok?json({ok:true}):error(d.msg||d.error_description||'Could not resend code',400)}],
 'POST /api/auth/code':[async({body})=>{const b=body as any;if(!b?.email)return error('Email is required',400);const k=await key();const r=await fetch(`${SUPABASE_URL}/auth/v1/otp`,{method:'POST',headers:{apikey:k,'Content-Type':'application/json'},body:JSON.stringify({email:String(b.email).trim().toLowerCase(),create_user:false})});const d=await r.json();return r.ok?json({ok:true}):error(d.msg||d.error_description||'Could not send sign-in code',400)}],
 'POST /api/auth/verify-code':[async({body})=>{const b=body as any;const k=await key();const r=await fetch(`${SUPABASE_URL}/auth/v1/verify`,{method:'POST',headers:{apikey:k,'Content-Type':'application/json'},body:JSON.stringify({email:String(b.email).trim().toLowerCase(),token:String(b.token).trim(),type:'email'})});const d=await r.json();return r.ok?json({access_token:d.access_token,refresh_token:d.refresh_token,user:d.user}):error(d.msg||d.error_description||'Invalid code',400)}],
 'POST /api/auth/signin':[async({body})=>{const b=body as any;if(!b?.email||!b?.password)return error('Email and password are required',400);const k=await key();const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:k,'Content-Type':'application/json'},body:JSON.stringify({email:b.email,password:b.password})});const d=await r.json();return r.ok?json({access_token:d.access_token,refresh_token:d.refresh_token,user:d.user}):error(d.error_description||'Sign in failed',401)}],
 'GET /api/auth/me':[async(ctx)=>{const u=await userFrom(ctx);return u?json({user:u}):error('Unauthorized',401)}],
 'GET /api/categories':[async()=>{const {r,data}=await sb('/rest/v1/categories?is_active=eq.true&select=*&order=sort_order.asc');return r.ok?json(data):error('Could not load categories',500)}],
 'GET /api/products':[async({query})=>{let path='/rest/v1/products?is_available=eq.true&select=*,categories(name)&order=created_at.desc';if(query.category)path+=`&category_id=eq.${encodeURIComponent(query.category)}`;if(query.featured==='true')path+='&is_featured=eq.true';const {r,data}=await sb(path);return r.ok?json(data):error('Could not load products',500)}],
 'POST /api/orders':[async(ctx)=>{const u=await userFrom(ctx);if(!u)return error('Sign in required',401);const b=ctx.body as any;if(!Array.isArray(b?.items)||!b.items.length)return error('Your cart is empty',400);const ids=[...new Set(b.items.map((x:any)=>x.product_id))];const {r,data:products}=await sb(`/rest/v1/products?id=in.(${ids.join(',')})&is_available=eq.true&select=id,name,price`);if(!r.ok||products.length!==ids.length)return error('A menu item is unavailable',400);const items=b.items.map((x:any)=>{const p=products.find((p:any)=>p.id===x.product_id);return {...x,product_name:p.name,unit_price:Number(p.price),line_total:Number(p.price)*Number(x.quantity)}});const subtotal=items.reduce((s:number,x:any)=>s+x.line_total,0);const deliveryFee=b.order_type==='delivery'?Number(b.delivery_fee||0):0;const orderNumber=`CH-${Date.now().toString().slice(-8)}`;const {r:or,data:orders}=await sb('/rest/v1/orders',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{user_id:u.id,order_number:orderNumber,order_type:b.order_type||'delivery',status:'pending',subtotal,delivery_fee:deliveryFee,total:subtotal+deliveryFee,payment_method:b.payment_method||'cash_on_delivery',payment_status:b.payment_method==='card'?'pending':'unpaid',customer_name:b.customer_name||u.user_metadata?.full_name||'Customer',customer_phone:b.customer_phone||'',notes:b.notes||null}])});if(!or.ok)return error('Could not create order',500);const order=orders[0];const {r:ir}=await sb('/rest/v1/order_items',{method:'POST',body:JSON.stringify(items.map((x:any)=>({...x,order_id:order.id})))});if(!ir.ok){await sb(`/rest/v1/orders?id=eq.${order.id}`,{method:'DELETE'});return error('Could not save order items',500)}return json({...order,items},201)}],
 'GET /api/orders':[async(ctx)=>{const u=await userFrom(ctx);if(!u)return error('Sign in required',401);const {r,data}=await sb(`/rest/v1/orders?user_id=eq.${u.id}&select=*,order_items(*)&order=created_at.desc`);return r.ok?json(data):error('Could not load orders',500)}],
 'GET /api/admin/products':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const {r,data}=await sb('/rest/v1/products?select=*,categories(name)&order=created_at.desc');return r.ok?json(data):error('Could not load products',500)}],
 'POST /api/admin/products':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const b=ctx.body as any;if(!b?.name||b.price===undefined)return error('Name and price are required',400);const payload={name:b.name,slug:b.slug||slugify(b.name),description:b.description||null,price:Number(b.price),category_id:b.category_id||null,image_url:b.image_url||null,is_available:b.is_available!==false,is_featured:b.is_featured===true};const {r,data}=await sb('/rest/v1/products',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([payload])});return r.ok?json(data[0],201):error('Could not create product',400)}],
 'PATCH /api/admin/products/:id':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const {r,data}=await sb(`/rest/v1/products?id=eq.${ctx.params.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(ctx.body)});return r.ok?json(data?.[0]):error('Could not update product',400)}],
 'DELETE /api/admin/products/:id':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const {r}=await sb(`/rest/v1/products?id=eq.${ctx.params.id}`,{method:'DELETE'});return r.ok?json({ok:true}):error('Could not delete product',400)}],
 'GET /api/admin/analytics':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const {r,data}=await sb('/rest/v1/orders?select=id,total,status,created_at,payment_status&order=created_at.desc&limit=1000');if(!r.ok)return error('Could not load analytics',500);const start=new Date();start.setHours(0,0,0,0);const today=data.filter((x:any)=>new Date(x.created_at)>=start);return json({orders:data.length,revenue:data.reduce((s:number,x:any)=>s+Number(x.total||0),0),todayOrders:today.length,todayRevenue:today.reduce((s:number,x:any)=>s+Number(x.total||0),0),pending:data.filter((x:any)=>['pending','confirmed','preparing'].includes(x.status)).length})}],
 'GET /api/admin/audit-logs':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const {r,data}=await sb('/rest/v1/audit_logs?select=*&order=created_at.desc&limit=100');return r.ok?json(data):error('Could not load audit log',500)}],
 'POST /api/payments/initialize':[async(ctx)=>{const u=await userFrom(ctx);if(!u)return error('Sign in required',401);const pk=await secrets.readSecret('PAYSTACK_SECRET_KEY');if(!pk)return error('Paystack is not configured. Add PAYSTACK_SECRET_KEY to AppDeploy secrets.',503);const b=ctx.body as any;const amount=Math.round(Number(b.amount)*100);if(!amount)return error('Invalid amount',400);const reference=`CH-${crypto.randomUUID()}`;const r=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${pk}`,'Content-Type':'application/json'},body:JSON.stringify({email:u.email,amount:String(amount),currency:'NGN',reference,channels:['card','bank','bank_transfer','ussd','qr'],metadata:{order_id:b.order_id||null,user_id:u.id}})});const d=await r.json();return r.ok&&d.status?json(d.data):error(d.message||'Could not initialize payment',400)}],
 'GET /api/admin/product-image/health':[async()=>json({ok:true})],
 'POST /api/admin/categories':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const b=ctx.body as any;const {r,data}=await sb('/rest/v1/categories',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{name:b.name,description:b.description||null,sort_order:Number(b.sort_order||0),is_active:true}])});return r.ok?json(data[0],201):error('Could not create category',400)}],
 'GET /api/admin/categories':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const {r,data}=await sb('/rest/v1/categories?select=*&order=sort_order.asc');return r.ok?json(data):error('Could not load categories',500)}],
 'GET /api/admin/orders':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const {r,data}=await sb('/rest/v1/orders?select=*,order_items(*)&order=created_at.desc');return r.ok?json(data):error('Could not load orders',500)}],
 'PATCH /api/admin/orders/:id/status':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const allowed=['pending','confirmed','preparing','ready','out_for_delivery','delivered','cancelled'];const status=(ctx.body as any)?.status;if(!allowed.includes(status))return error('Invalid status',400);const {r,data}=await sb(`/rest/v1/orders?id=eq.${ctx.params.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status,updated_at:new Date().toISOString()})});return r.ok?json(data?.[0]):error('Could not update order',400)}],
 'POST /api/admin/product-image':[async(ctx)=>{if(!await adminFrom(ctx))return error('Admin access required',403);const b=ctx.body as any;if(typeof b?.data_url!=='string'||!b.data_url.startsWith('data:image/'))return error('Image data is required',400);const match=b.data_url.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!match)return error('Invalid image',400);const contentType=match[1],bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));const ext=contentType.split('/')[1].replace('jpeg','jpg');const path=`products/${crypto.randomUUID()}.${ext}`;const k=await key();const rr=await fetch(`${SUPABASE_URL}/storage/v1/object/product-images/${path}`,{method:'POST',headers:{Authorization:`Bearer ${k}`,apikey:k,'Content-Type':contentType,'x-upsert':'false'},body:bytes});if(!rr.ok)return error('Image upload failed',500);return json({url:`${SUPABASE_URL}/storage/v1/object/public/product-images/${path}`,path})}],
});
